project:
  type: website

website:
  title: "Onesime"
  favicon: "My_portfolio/favicon.ico"
  twitter-card: true
  open-graph: true
  cookie-consent:
    type: express
    style: interstitial
    palette: light
  navbar:
    left:
      - icon: file-bar-graph-fill
        text: "Mon portfolio"
        file: page-projet/page1.qmd
        aria-label: Projects
      - text: "Curriculum Vitae"
        file: cv.qmd
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      - icon: twitter
        href: https://X.com
    right:
      - icon: cloud-upload
        text: "Publier"
        href: https://github.com/Onesime165/portfolio/settings/pages
        aria-label: Publish
    background: "#2c3e50"
    pinned: true
    collapse: true

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Look at the code"

editor: visual

execute:
  freeze: auto
